print(" Set Disscussion ")

setA = set({1,2,3,2,1})
print(setA)
print("Add a element in setA ")
setA.add(4)
print(setA)
print("Add more element in setA ")
setA.update({5,6})
print(setA)
print("Remove a element from setA ")
setA.remove(1)
print(setA)
print("Remove a element from setA using discard")
setA.discard(9)
print(setA)
print("Clear the set using clear() method ")
setA.clear()
print(setA)